# Generated by Django 4.0.4 on 2022-06-07 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GenericApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Student1',
        ),
    ]
