# Generated by Django 4.0.5 on 2022-06-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_person_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=10),
        ),
    ]
